version: "3"

services:
  server:
    build: .
    container_name: "usurt_timetable_telegram_bot"
    command: python run.py
    restart: on-failure
    env_file: .env
    environment:
      - TELEGRAM_BOT_TOKEN
      - REDIS_HOST
    volumes:
      - .:/usurt_timetable_telegram_bot
  redis:
    image: redis
    restart: on-failure
    container_name: 'redis'
    command: redis-server
    env_file: .env
    environment:
      - TELEGRAM_BOT_TOKEN
      - REDIS_HOST
    ports:
      - '6379:6379'